tap "homebrew/cask"
#Brew
brew "ack"
brew "berglas"	
brew "ca-certificates"
brew "circleci"
brew "colima"
brew "curl"
brew "docker"
brew "git"
brew "git"
brew "groovy"
brew "helm"
brew "jq"
brew "kubectl"
brew "leiningen"
brew "micronaut"
brew "node"
brew "openjdk@11"
brew "php" #shrug 
brew "postgres"
brew "python@3.9"
brew "readline"
brew "terraform"
brew "thefuck"
brew "tree"
brew "watch"
brew "wget"
brew "yamllint"
brew "yarn"

#Cask
brew "neovim"
cask "alfred"
cask "discord"
cask "divvy"
cask "google-chrome"
cask "google-cloud-sdk"
cask "grandperspective" 
cask "intellij-idea"
cask "iterm2"
cask "rescuetime"
cask "spotify"
cask "tomighty"
cask "zoom"
