tap "homebrew/cask"
tap "heroku/brew"

#brew
brew "ack"
brew "berglas"	
brew "ca-certificates"
brew "circleci"
brew "colima"
brew "curl"
brew "docker"
brew "flyctl"
brew "fzf"
brew "git"
brew "groovy"
brew "helm"
brew "jq"
brew "k6"
brew "kubectl"
brew "leiningen"
brew "micronaut"
brew "node"
brew "openjdk@11"
brew "peco"
brew "php" #shrug 
brew "postgres"
brew "python@3.9"
brew "rbenv"
brew "heroku"
brew "readline"
brew "starship"
brew "terraform"
brew "thefuck"
brew "tree"
cask "visual-studio-code"
brew "watch"
brew "wget"
brew "yamllint"
brew "yarn"
brew "yq"
brew "warrensbox/tap/tfswitch"
brew "kubectx"

#Cask
brew "neovim"
cask "alfred"
cask "discord"
cask "divvy"
cask "google-chrome"
cask "google-cloud-sdk"
cask "grandperspective" 
cask "intellij-idea"
cask "iterm2"
cask "rescuetime"
cask "postman"
cask "spotify"
cask "tomighty"
cask "zoom"
